# Welcome {.unnumbered}

This is the website for the 1st edition of **"LLM one0one"**.
This book will teach you how to do deal with LLM.

In this book, you will find a practicum of skills for Large Language Model as well as Small Language Model.

This website is and will always be free, licensed under the [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) License.
If you'd like a physical copy of the book, you can order it on [Amazon](https://www.amazon.in/
If you appreciate reading the book for free and would like to give back, please make a donation to [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): the [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (which appears on the cover of R4DS) is a critically endangered parrot native to New Zealand; there are only 244 left.

If you speak another language, you might be interested in the freely available translations of the 1st edition:

-   [Spanish](http://es.r4ds.hadley.nz)
-   [Italian](https://it.r4ds.hadley.nz)
-   [Turkish](https://tr.r4ds.hadley.nz)
-   [Portuguese](https://pt.r4ds.hadley.nz)


Please note that R4DS uses a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html).
By contributing to this book, you agree to abide by its terms.
